### ISSUE TITLE
New Business Goal is placed.

### ISSUE THREAD

**Issue by jose598** [rohusemer/SII-WORKSHOPS-EDUCACION_CONTINUA#2]
Dear support team, we are satisfied about your hard work during this last year. On this new year we want to be bigger and better. In the meeting with the Accounting Department and Business Intelligent Group, we proposed some changes with the intention of improving our service and getting more customers. The new business rule establishes: If the customer is married and has more than 30 years old but younger than 60, then $50 must be decreased to the base premium for each one, however if the customer is single, woman and older than 60 years old , she will receive a discount for around $50.

You need to know that all rules should be maintained how it was coming. Our request should be added to the existing one and the result should be calculated with all rules applied.

**Comment by densreye** [comment]
The requirement is reviewed.

**Comment by densreye** [comment]
@densreye will take care of the development and analysis
@rohusemer will be in charge of carrying out the tests

**Comment by jose598** [comment]
Thank you @densreye . I will wait for your response

**Comment by densreye** [comment]
@jose598 
[RFD_CarInsurance.docx](https://github.com/rohusemer/SII-WORKSHOPS-EDUCACION_CONTINUA/files/7902350/RFD_CarInsurance.docx)

Attached RFD for your review and acceptance

**Comment by densreye** [comment]
@jose598 the improvements were uploaded, we consider that they are the tests carried out the calculations are correct

Changes: https://github.com/rohusemer/SII-WORKSHOPS-EDUCACION_CONTINUA/blob/Gesti%C3%B3n_de_Incidencias/ec.edu.espol.workshops/lib/src/main/java/ec/edu/espol/workshops/Carlnsurance.java#:~:text=%7D-,if((getEstado().equals(%22Casado%22))%7C%7C(getSexo().equals(%22F%22))%20%7C%7C%20(getSexo().equals(%22M,%7D,-%7D

**Comment by jose598** [comment]
@densreye Thank you. 
I approved your changes and everything is OK. 


Please close the issue.

**Comment by densreye** [comment]
The issue was approved
